### ISSUE TITLE
HDR count between 2 values

### ISSUE THREAD

**Issue by assaad** [HdrHistogram/HdrHistogram_c#91]
Hello, thanks a lot for this lib, very great work. I would like to know if there is a better way to get the number of counts between 2 values other than iterating on them one by one and adding the result of 
```hdr_count_at_value(histogram,i)```
Is there a method hdr_count_interval(histogram,i,j)

**Comment by giltene** [comment]
The [recorded values iterator](https://github.com/HdrHistogram/HdrHistogram_c/blob/706a9e06477472e4a34531640c15a641ba2c83cb/test/hdr_histogram_log_test.c#L627) is probably best use for this purpose. You can see an example of iterating through recorded values in a histogram [here](https://github.com/HdrHistogram/HdrHistogram_c/blob/706a9e06477472e4a34531640c15a641ba2c83cb/test/hdr_histogram_log_test.c#L627), and adapt it to you task (of e.g. adding all the counts for values that are >= the start of the rage and < the end of the range).

It is important to use the iterators for this purpose (or alternatively use hdr_next_non_equivalent_value() to increment in a value loop), as opposed to e.g. just looping on all integer values in the race you are looking at, to avoid over-counting or counting the same recorded values more than once due to nature of value quantization in hdr_histogram. For each value, there is a range of equivalent values [hdr_lowest_equivalent_value(v) ... hdr_next_non_equivalent_value) and all values in that range share a single count. That means you only want to accumulate that count once per equivalent value range, and not once per integer value...

The recorded values iterator is a convenient iterator to use to only visit values that have non-zero counts, and to only each equivalent value range once.

**Comment by assaad** [comment]
Perfect, thank you

**Comment by assaad** [comment]
Just one more question please: if my histogram is from 10 to 10,000. and i want to iterate from 100 to 200, is there a way to initialize the iterator to start at the closest value of 100? or should i always iterate from the start? 
Many thanks

**Comment by mikeb01** [comment]
You would need to iterate from the start.
